version: '3'
services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - '5673:5672'
      - '15673:15672'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'
  redis:
    container_name: redis
    image: redis
    ports:
      - '6380:6379'
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.7.1
    depends_on:
      - elasticsearch
    ports:
      - '5602:5601'
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
        - '9201:9200'

  node:
    container_name: docker-node
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - rabbit
      - redis
      - mongo
    depends_on:
      - rabbit
      - mongo
      - redis
      - kibana
      - elasticsearch
    env_file:
      - .env
    command: [
      "./wait-for-it.sh", "rabbit:5672", "--",
      "./wait-for-it.sh", "mongo:27017", "--",
      "./wait-for-it.sh", "redis:6379", "--",
      "./wait-for-it.sh", "kibana:5601", "--",
      "./wait-for-it.sh", "elasticsearch:9200", "--",
      "npm", "start"
    ]